# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'DemoAppiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod ‘SmartDeviceLink’, ‘~> 6.2’

  target 'DemoAppiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoAppiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
